apiVersion: v1
kind: Service
metadata:
  name: kubeai-frontend
  namespace: kubeai
  labels:
    app: kubeai-frontend
spec:
  type: NodePort
  selector:
    app: kubeai-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 39090